name: Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Firebase Emulators
        run: npm install -g firebase-tools
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          browser: chrome
          wait-on: "http://localhost:4200"
        env:
          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          FIREBASE_AUTH_EMULATOR_HOST: "localhost:9099"
          FIRESTORE_EMULATOR_HOST: "localhost:8080"
      - name: Jest run
        run: npm run test:ci
      - name: Firestore security rules
        run: npm run test:rules:ci
